### ISSUE TITLE
Marco 1, tarefa 01 -  Design das Telas

### ISSUE THREAD

**Issue by gustavofcamposs** [gustavofcamposs/Toy-House#5]
## Tarefa Marco 1: Etapa 01

- **Tela Inicial Simples**:
  - **Header** com duas opções: "Login" e "Cadastrar", permitindo que o cliente acesse suas funcionalidades.
  
- **Home para Funcionário**:
  - Interface dedicada para funcionários, contendo uma única funcionalidade de cadastrar produtos no ToyHouse
<br/>

## Como deve ser Entregue:

- **Envio de Capturas de Tela**:
  - Após a conclusão das telas, **enviar capturas de tela** das interfaces desenvolvidas.
  - **Como anexar imagens**:
    - Arraste e solte as imagens diretamente na área de comentário desta issue ou clique no ícone de imagem no editor para fazer o upload.
    - O GitHub gerará automaticamente links para as imagens, que serão exibidos e documentados aqui.

**Comment by ArthurFiorin** [comment]
![Image](https://github.com/user-attachments/assets/740bfc1a-9837-4da7-9bd9-516fb4a363f0)

Imagem referente a tabela de cadastro de funcionários/clientes.

![Image](https://github.com/user-attachments/assets/a1afe91d-57b7-42e0-baeb-2a982eee424e)

Imagem referente a tabela de cadastro de produtos.

**Comment by gustavofcamposs** [comment]
![Image](https://github.com/user-attachments/assets/af3aea48-f8f5-47dd-9fa4-d638f52fe155)
Imagem referente a Home dos cliente, necessário criação somente do Menu de acordo com o que foi solicitado pelo Professor do PI 

<br>

Marco 01
